export const ROUTE = {
  HOME: "/",
  HDMV: "/hoa-don-mua-vao",
  HDMV_TatCa: "/hoa-don-mua-vao/tat-ca",
  HDMV_Huy: "/hoa-don-mua-vao/da-huy",
  HDMV_ThayThe: "/hoa-don-mua-vao/da-thay-the",
  HDMV_DaDC: "/hoa-don-mua-vao/da-dieu-chinh",
  HDMV_XuatBangKe: "/hoa-don-mua-vao/xuat-bang-ke",
  HDBR: "/hoa-don-ban-ra",
  HDBR_TatCa: "/hoa-don-ban-ra/tat-ca",
  HDBR_Huy: "/hoa-don-ban-ra/da-huy",
  HDBR_ThayThe: "/hoa-don-ban-ra/da-thay-the",
  HDBR_DaDC: "/hoa-don-ban-ra/da-dieu-chinh",
  HDBR_XuatBangKe: "/hoa-don-ban-ra/xuat-bang-ke",
  LOGIN: "/login",
  LOGOUT: "/logout",
  NOT_FOUND: "*",
};
